//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewToDoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBL { get; set; }
        public int MaCV { get; set; }
        public int MaNV { get; set; }
        public string BinhLuan1 { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
