//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewToDoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongViec()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietCV_NV = new HashSet<ChiTietCV_NV>();
            this.TapTins = new HashSet<TapTin>();
        }
    
        public int MaCV { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetKhuc { get; set; }
        public string TrangThai { get; set; }
        public string PhamVi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCV_NV> ChiTietCV_NV { get; set; }
        public virtual TrangThai TrangThai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TapTin> TapTins { get; set; }
    }
}
