//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewToDoList.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class log
    {
        public int id { get; set; }
        [DisplayName("Nhân viên")]
        public int MaNV { get; set; }
        [DisplayName("Hoạt động")]
        public string HoatDong { get; set; }
        [DisplayName("Khu vực tác động")]
        public string Bang { get; set; }
        [DisplayName("Thời gian")]
        public System.DateTime ThoiGian { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
