//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewToDoList.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TapTin
    {
        public int MaTT { get; set; }
        [DisplayName("Đường dẫn")]
        public string DuongDan { get; set; }
        [DisplayName("Tên file")]
        public int NhanVienUp { get; set; }
        public int MaCV { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
